## Ansible Generated ##

### LEAF2B ###


### Leaf Info ###
l3leaf_node_group: DC1_LEAF2
switch_platform: 7280R
leaf_bgp_as: 65003
leaf_id: 20
switch_mgmt_ip: 192.168.100.34/24
leaf_filter_tenants: ['all']
leaf_filter_tags: ['opzone', 'web', 'app', 'db']
leaf_allowed_vrfs: ['A']
leaf_allowed_svis: [10, 20, 30, 40]
leaf_allowed_vlans: [10, 20, 30, 40]
leaf_mlag: True
leaf_mlag_group: DC1_LEAF2
leaf_mlag_role: secondary
leaf_mlag_peer: LEAF2A
leaf_mlag_ip: 37
leaf_mlag_peer_ip: 36
leaf_mlag_peer_id: 19

service_routing_protocols_model: multi-agent
ip_routing: true

### Hardware Counters
hardware_counters:

### Daemon TerminAttr
daemon_terminattr:
  ingestgrpcurl:
    ips:
      - 192.168.100.240
    port: 9910
  ingestauth_key: magickey02122020
  ingestvrf: MGMT
  smashexcludes: "ale,flexCounter,hardware,kni,pulse,strata"
  ingestexclude: "/Sysdb/cell/1/agent,/Sysdb/cell/2/agent"

vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199

### Event Monitor ###
event_monitor:
  enabled: true

### Event Handler ###
event_handlers:

### Load Interval ###
load_interval:

### Queue Monitor Lenght ###
queue_monitor_length:
  enabled: true

### Logging ###
logging:

### Name Servers ###
name_server:
  source:
    vrf: MGMT
  nodes:
    - 192.168.70.1

### NTP Servers ###
ntp_server:
  local_interface:
    vrf: MGMT
    interface: Management1
  nodes:
    - 216.239.35.4

### Redundancy ###
redundancy:

### Spanning-tree ###
spanning_tree:
  mode: mstp
  priority: 4096
  no_spanning_tree_vlan: 4094


### AAA authorization ###
aaa_authorization:

### local users ###
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: $6$xTFjLEjlpX/ZvgNp$3ARB.DYuWuJDHzph652u7BAkyQ6jni/NZqKRUQBDJxUL83QuL6/HBY4tL/UXuKr1n00yjwNHtUBn.UbixdLai0
  arista:
    privilege: 15
    sha512_password: $6$RO7KPjCB0BtlFgcd$/7Lv7Pjj3/OUOIUmqk0NmB8218tnq3Qcjb20pF4Xb3VaoMEuXShWVpFGU.YTYBuQ5.e3SXOLrIEfXpFegrQDX.
  cvpadmin:
    privilege: 15
    sha512_password: $6$u5wM2GSl324m5EF0$AM98W2MI4ISBciPXm6be8Q3RTykF3dCd2W3btVvhcBBKvKHjfbkeJfesbEWMcrYlbzzZbWdBcxF6U/Pe3xBYF1

### Clock Timezone ###
clock:
  timezone: America/Detroit

### VLANs ###
vlans:
## mlag vlans ##
  4093:
    tenant: system
    name: LEAF_PEER_L3
    trunk_groups:
      - LEAF_PEER_L3
  4094:
    tenant: system
    name: MLAG_PEER
    trunk_groups:
      - MLAG

## Tenant_A ##
  10:
    tenant: Tenant_A
    name: Ten-opzone
  20:
    tenant: Tenant_A
    name: Twenty-web
  30:
    tenant: Tenant_A
    name: Thirty-app
  40:
    tenant: Tenant_A
    name: Forty-db
  3050:
    tenant: Tenant_A
    name: MLAG_iBGP_A
    trunk_groups:
      - LEAF_PEER_L3

### VRFs ###
vrfs:
  MGMT:
    ip_routing: False
## Tenant_A ##
  A:
    tenant: Tenant_A
    ip_routing: true

### bfd multihop ###
bfd_multihop:
  interval: 300
  min_rx: 300
  multiplier: 3

### Port-Channel Interfaces ###
port_channel_interfaces:
## mlag peer-link ##
  Port-Channel47:
    description: MLAG_PEER_LEAF2A_Po47
    vlans: "2-4094"
    mode: trunk
    trunk_groups:
      - LEAF_PEER_L3
      - MLAG
  Port-Channel10:
    description: HostC_Po1
    vlans: 30
    mode: access
    mlag: 10
    spanning_tree_portfast: edge

### Ethernet Interfaces ###
ethernet_interfaces:
  Ethernet1:
    peer: SPINE1
    peer_interface: Ethernet3
    peer_type: spine
    description: P2P_LINK_TO_SPINE1_Ethernet3
    mtu: 9216
    type: routed
    ip_address: 10.1.1.77/31
  Ethernet2:
    peer: SPINE2
    peer_interface: Ethernet3
    peer_type: spine
    description: P2P_LINK_TO_SPINE2_Ethernet3
    mtu: 9216
    type: routed
    ip_address: 10.1.1.79/31
## mlag interfaces ##
  Ethernet47:
    peer: LEAF2A
    peer_interface: Ethernet47
    peer_type: mlag_peer
    description: MLAG_PEER_LEAF2A_Ethernet47
    channel_group:
      id: 47
      mode: active
  Ethernet48:
    peer: LEAF2A
    peer_interface: Ethernet48
    peer_type: mlag_peer
    description: MLAG_PEER_LEAF2A_Ethernet48
    channel_group:
      id: 47
      mode: active
  Ethernet10:
    peer: HostC
    peer_interface: E2
    peer_type: server
    description: HostC_E2
    mode: access
    vlans: 30
    spanning_tree_portfast: edge
    channel_group:
      id: 10
      mode: "active"
  Ethernet11:
    peer: HostD
    peer_interface: E1
    peer_type: server
    description: HostD_E1
    mode: access
    vlans: 10
    spanning_tree_portfast: edge
    spanning_tree_bpdufilter: True


### Loopback Interfaces ###
loopback_interfaces:
  Loopback0:
    description: EVPN_Overlay_Peering
    ip_address: 1.1.1.22/32

  Loopback1:
    description: VTEP_VXLAN_Tunnel_Source
    ip_address: 2.2.2.21/32
## Tenant_A ##
  Loopback100:
    description: A_VTEP_DIAGNOSTICS
    vrf: A
    ip_address: 10.255.1.22/32

### Management Interfaces ###
management_interfaces:
  Management1:
    description: oob_management
    vrf: MGMT
    ip_address: 192.168.100.34/24
    gateway: 192.168.100.1

### VLAN Interfaces ###
vlan_interfaces:
  Vlan4093:
    description: MLAG_PEER_L3_PEERING
    ip_address: 10.255.251.37/31
  Vlan4094:
    description: MLAG_PEER
    ip_address: 10.255.252.37/31
    no_autostate: true
    mtu: 9216
## Tenant_A ##
  Vlan10:
    tenant: Tenant_A
    tags: ['opzone']
    description: Ten-opzone
    vrf: A
    ip_address_virtual: 10.10.10.1/24
  Vlan20:
    tenant: Tenant_A
    tags: ['web']
    description: Twenty-web
    vrf: A
    ip_address_virtual: 20.20.20.1/24
  Vlan30:
    tenant: Tenant_A
    tags: ['app']
    description: Thirty-app
    vrf: A
    ip_address_virtual: 30.30.30.1/24
  Vlan40:
    tenant: Tenant_A
    tags: ['db']
    description: Forty-db
    vrf: A
    ip_address_virtual: 40.40.40.1/24
  Vlan3050:
    tenant: Tenant_A
    type: underlay_peering
    description: "MLAG_PEER_L3_iBGP: vrf A"
    vrf: A
    ip_address: 10.255.251.37/31

### VxLAN interface ###
vxlan_tunnel_interface:
  Vxlan1:
    description: LEAF2B_VTEP
    source_interface: Loopback1
    virtual_router:
      encapsulation_mac_address: "mlag-system-id"
    vxlan_udp_port: 4789
    vxlan_vni_mappings:
      vlans:
## Tenant_A ##
        10:
          vni: 10010
        20:
          vni: 10020
        30:
          vni: 10030
        40:
          vni: 10040
      vrfs:
## Tenant_A ##
        A:
          vni: 51

### TCAM Profiles ###
tcam_profile:
  - vxlan-routing

### MAC address table ###
mac_address_table:

ip_virtual_router_mac_address: aa:aa:bb:bb:cc:cc

virtual_source_nat_vrfs:
## Tenant_A ##
  A:
    ip_address: 10.255.1.22

### static routes ###
static_routes:
  - vrf: MGMT
    destination_address_prefix: 0.0.0.0/0
    gateway: 192.168.100.1

### prefix-lists ###
prefix_lists:
  PL-LOOPBACKS-EVPN-OVERLAY:
    sequence_numbers:
      10:
        action: "permit 1.1.1.0/24 eq 32"
      20:
        action: "permit 2.2.2.0/24 eq 32"
  PL-P2P-UNDERLAY:
    sequence_numbers:
      10:
        action: "permit 10.1.1.0/24 le 31"
      20:
        action: "permit 10.255.251.0/24 le 31"

### MLAG Configuration ###
mlag_configuration:
  domain_id: DC1_LEAF2
  local_interface: Vlan4094
  peer_address: 10.255.252.36
  peer_address_heartbeat:
    peer_ip: 192.168.100.33
    vrf: MGMT
  dual_primary_detection_delay: 5
  peer_link: Port-Channel47
  reload_delay_mlag: 780
  reload_delay_non_mlag: 1020

### route-maps ###
route_maps:
  RM-CONN-2-BGP:
    sequence_numbers:
      10:
        type: permit
        match: "ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY"
### Routing - BGP ###
router_bgp:
  as: 65003
  router_id: 1.1.1.22
  bgp_defaults:
    - update wait-install
    - no bgp default ipv4-unicast
    - distance bgp 20 200 200
    - graceful-restart restart-time 300
    - graceful-restart
    - maximum-paths 2 ecmp 2
  peer_groups:
    IPv4-UNDERLAY-PEERS:
      type: ipv4
      remote_as: 65001
      password: "AQQvKeimxJu+uGQ/yYvv9w=="
      maximum_routes: 12000
      send_community: true
    EVPN-OVERLAY-PEERS:
      type: evpn
      remote_as: 65001
      update_source: Loopback0
      bfd: true
      ebgp_multihop: 3
      password: "q+VNViP5i4rVjW1cxFv2wA=="
      send_community: true
      maximum_routes: 0
    MLAG-IPv4-UNDERLAY-PEER:
      type: ipv4
      remote_as: 65003
      next_hop_self: true
      password: "vnEaG8gMeQf3d3cN6PktXQ=="
      maximum_routes: 12000
      send_community: true
  neighbors:
    10.1.1.76:
      peer_group: IPv4-UNDERLAY-PEERS
    10.1.1.78:
      peer_group: IPv4-UNDERLAY-PEERS
    1.1.1.1:
      peer_group: EVPN-OVERLAY-PEERS
    1.1.1.2:
      peer_group: EVPN-OVERLAY-PEERS
    10.255.251.36:
      peer_group: MLAG-IPv4-UNDERLAY-PEER
  redistribute_routes:
    connected:
      route_map: RM-CONN-2-BGP
  address_family_evpn:
    peer_groups:
      EVPN-OVERLAY-PEERS:
        activate: true
      IPv4-UNDERLAY-PEERS:
        activate: false
      MLAG-IPv4-UNDERLAY-PEER:
        activate: false
  address_family_ipv4:
    peer_groups:
      EVPN-OVERLAY-PEERS:
        activate: false
      IPv4-UNDERLAY-PEERS:
        activate: true
      MLAG-IPv4-UNDERLAY-PEER:
        activate: true
  vlan_aware_bundles:
## Tenant_A ##
    A:
      rd: "1.1.1.22:51"
      route_targets:
        both:
          - "51:51"
      redistribute_routes:
        - learned
      vlan: 10,20,30,40
  vlans:
  vrfs:
## Tenant_A ##
    A:
      router_id: 1.1.1.22
      rd: "1.1.1.22:51"
      route_targets:
        import:
          evpn:
            - "51:51"
        export:
          evpn:
            - "51:51"
      neighbors:
        10.255.251.36:
          peer_group: MLAG-IPv4-UNDERLAY-PEER
      redistribute_routes:
        - connected

### Routing - OSPF ###
router_ospf:

### Queue Monitor Streaming ###
queue_monitor_streaming:
  enable: True
  vrf: MGMT

### Management API http ###
management_api_http:
  enable_https: True
  enable_vrfs:
    MGMT:
