---
- name: Build Switch configuration
  hosts: DC1_FABRIC
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  tasks:
    - name: 'create cvp structure config folder: {{documentation_dir_name}}'
      tags: [build, generate]
      file:
        path: '{{playbook_dir}}/intended/structured_configs/cvp/'
        state: directory
        mode: 0755
      delegate_to: localhost
    - name: 'reset local folders for output'
      tags: [build, generate]
      import_role:
        name: arista.avd.build_output_folders
    - name: generate intended variables
      tags: [build, generate]
      import_role:
        name: arista.avd.eos_l3ls_evpn
    - name: generate device intended config and documentation
      tags: [build, generate]
      import_role:
        name: eos_cli_config_gen

- name: Configuration deployment with CVP
  hosts: cv_server
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  tasks:
    - name: run CVP provisioning
      import_role:
        name: arista.avd.eos_config_deploy_cvp
      vars:
        container_root: 'DC1_FABRIC'
        configlets_prefix: 'DC1-AVD'
        device_filter: 'DC1'
        state: present
