# Nashua EVE-NG LAB shared attributes

# local users
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: "$6$Df86J4/SFMDE3/1K$Hef4KstdoxNDaami37cBquTWOTplC.miMPjXVgQxMe92.e5wxlnXOLlebgPj8Fz1KO0za/RCO7ZIs4Q6Eiq1g1"

  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: "$6$rZKcbIZ7iWGAWTUM$TCgDn1KcavS0s.OV8lacMTUkxTByfzcGlFlYUWroxYuU7M/9bIodhRO7nXGzMweUxvbk8mJmQl8Bh44cRktUj."

# Cloud Vision server
cvp_instance_ips:
  - 192.168.200.11

cvp_ingestauth_key: telarista

# OOB Management network default gateway.
mgmt_gateway: 192.168.200.1

# dns servers.
name_servers:
 - 192.168.200.5
 - 8.8.8.8

# NTP Servers IP or DNS name, first NTP server will be prefered, and sourced from Managment
ntp_servers:
  - 0.north-america.pool.ntp.org
  - 1.north-america.pool.ntp.org

###  EOS Aliases ###
# aliases: |
#   alias copp show policy-map copp copp-system-policy
#   alias help bash echo -e "sib : show ip bgp\nsibs : show ip bgp summary\nsiib : show ip int brief\nsir : show ip route\nsenz : show interface counter error | nz\nsnz : show interface counter | nz\nsps : show port-channel summary\nspd : show port-channel detail all\nsqnz : show interface counter queue | nz\nsrnz : show interface counter rate | nz\nsmac : show mac address-table dynamic\nsarp : show ip arp\ncopp : show policy-map copp copp-system-policy\ninfo : version, serial and mlag"
#   alias sarp show ip arp
#   alias senz show interface counter error | nz
#   alias sib show ip bgp
#   alias sibs show ip bgp summary
#   alias siib show ip int brief
#   alias sir show ip route
#   alias smac show mac address-table dynamic
#   alias snz show interface counter | nz
#   alias spd show port-channel %1 detail all
#   alias sps show port-channel summary
#   alias sqnz show interface counter queue | nz
#   alias srnz show interface counter rate | nz
#   !
#   alias info
#      10 bash SERIAL=$(FastCli -p 15 -c 'show version' | grep Serial | tr -s ' ' | cut -d ' ' -f 3 | tr -d '\r');echo -e "SN : $SERIAL"
#      20 bash VERSION=$(FastCli -p 15 -c 'show version' | grep image | tr -s ' ' | cut -d ' ' -f 4 | tr -d '\r');echo -e "EOS VERSION : $VERSION"
#      30 bash DOMAIN=$(FastCli -p 15 -c 'show mlag' | grep domain | tr -s ' ' | cut -d ' ' -f 3 | tr -d '\r');echo -e "MLAG DOMAIN : $DOMAIN"
#      40 bash STATE=$(FastCli -p 15 -c 'show mlag' | grep state | tr -s ' ' | cut -d ' ' -f 3 | tr -d '\r');echo -e "MLAG STATE : $STATE"

test: