---

# L3LS Fabric Values - update these values with caution, some changes could be disruptive.

fabric_name: DC1_FABRIC

# Upodate p2p mtu 9000 -> 1500
p2p_uplinks_mtu: 9216

# Point to Point Network Summary range, assigned as /31 for each uplink interfaces
# Assign range larger then total [ spines * total potential leafs * 2 ]
underlay_p2p_network_summary: 10.1.1.0/24

# IP address range for evpn loopback for all switches in fabric, assigned as /32s
# Assign range larger then total spines + total leafs switches
overlay_loopback_network_summary: 1.1.1.0/24

# VTEP VXLAN Tunnel source loopback IP for leaf switches, assigned in /32s
# Assign range larger then total leaf switches
vtep_loopback_network_summary: 2.2.2.0/24

# mlag pair IP assignment - assign blocks - Assign range larger then total spines + total leafs switches
mlag_ips:
  leaf_peer_l3: 10.255.251.0/24
  mlag_peer: 10.255.252.0/24

# Enable vlan aware bundles
vxlan_vlan_aware_bundles: true

# bgp peer groups passwords
bgp_peer_groups:
  IPv4_UNDERLAY_PEERS:
    password: "AQQvKeimxJu+uGQ/yYvv9w=="
  EVPN_OVERLAY_PEERS:
      password: "q+VNViP5i4rVjW1cxFv2wA=="
  MLAG_IPv4_UNDERLAY_PEER:
      password: "vnEaG8gMeQf3d3cN6PktXQ=="

# Spine Switches
spine:
  platform: vEOS-LAB
  bgp_as: 65001
  leaf_as_range: 65001-65199
  nodes:
    SPINE1:
      id: 1
      mgmt_ip: 192.168.100.31/24
    SPINE2:
      id: 2
      mgmt_ip: 192.168.100.35/24

# Leaf switch groups
# A maximum of two nodes can form a leaf group
# When two nodes are in a leaf group this will automatically form mlag pair

l3leaf:
  defaults:
    platform: vEOS-LAB
    spines: [ SPINE1, SPINE2 ]
    uplink_to_spine_interfaces: [ Ethernet1, Ethernet2 ]
    mlag_interfaces: [ Ethernet47, Ethernet48 ]
    spanning_tree_mode: mstp
    spanning_tree_priority: 4096
    virtual_router_mac_address : 00:dc:00:00:00:0a
  node_groups:
    DC1_LEAF1:
      bgp_as: 65002
      filter:
        tenants: [ all ]
        tags: [ opzone, web, app, db ]
      nodes:
        LEAF1A:
          id: 11
          mgmt_ip: 192.168.100.32/24
          spine_interfaces: [ Ethernet1, Ethernet1 ]
    DC1_LEAF2:
      bgp_as: 65003
      filter:
        tenants: [ all ]
        tags: [ opzone, web, app, db ]
      nodes:
        LEAF2A:
          id: 21
          mgmt_ip: 192.168.100.33/24
          spine_interfaces: [ Ethernet2, Ethernet2 ]
        LEAF2B:
          id: 22
          mgmt_ip: 192.168.100.34/24
          spine_interfaces: [ Ethernet3, Ethernet3 ]
